/* Generated by tools/build_art.py from art/. Do not edit. */
#ifndef POPEYE_GW_SEGMENTS_LANDSCAPE_H
#define POPEYE_GW_SEGMENTS_LANDSCAPE_H

#include <stdint.h>

#include "segments.h"

/* Complete LCD inventory; every entry has black-on-transparent art. */

#define LANDSCAPE_ART_COUNT 88
#define LANDSCAPE_SHEET_WIDTH 200
#define LANDSCAPE_SHEET_HEIGHT 301

static const SegmentArt landscape_art[SEG_COUNT] = {
  [SEG_AM] = { 131, 281, 192, 213, 4, 10 }, /* am */
  [SEG_BELL] = { 90, 296, 194, 63, 3, 4 }, /* bell */
  [SEG_BRUTUS + 0 * 3 + 0] = { 86, 0, 64, 0, 52, 51 }, /* brutus-left-idle */
  [SEG_BRUTUS + 0 * 3 + 2] = { 0, 0, 64, 0, 42, 69 }, /* brutus-left-strike */
  [SEG_BRUTUS + 0 * 3 + 1] = { 139, 0, 64, 0, 52, 51 }, /* brutus-left-windup */
  [SEG_BRUTUS + 1 * 3 + 0] = { 86, 70, 64, 178, 52, 50 }, /* brutus-right-idle */
  [SEG_BRUTUS + 1 * 3 + 2] = { 43, 0, 64, 160, 42, 68 }, /* brutus-right-strike */
  [SEG_BRUTUS + 1 * 3 + 1] = { 139, 70, 64, 178, 52, 50 }, /* brutus-right-windup */
  [SEG_CARGO + 0 * 5 + 0] = { 80, 264, 118, 50, 11, 15 }, /* cargo-0-0 */
  [SEG_CARGO + 0 * 5 + 1] = { 92, 264, 107, 50, 11, 15 }, /* cargo-0-1 */
  [SEG_CARGO + 0 * 5 + 2] = { 28, 264, 95, 50, 12, 15 }, /* cargo-0-2 */
  [SEG_CARGO + 0 * 5 + 3] = { 104, 264, 84, 50, 11, 15 }, /* cargo-0-3 */
  [SEG_CARGO + 0 * 5 + 4] = { 41, 264, 72, 50, 12, 15 }, /* cargo-0-4 */
  [SEG_CARGO + 1 * 5 + 0] = { 190, 236, 118, 78, 6, 16 }, /* cargo-1-0 */
  [SEG_CARGO + 1 * 5 + 1] = { 0, 264, 107, 78, 6, 16 }, /* cargo-1-1 */
  [SEG_CARGO + 1 * 5 + 2] = { 7, 264, 95, 78, 6, 16 }, /* cargo-1-2 */
  [SEG_CARGO + 1 * 5 + 3] = { 14, 264, 84, 78, 6, 16 }, /* cargo-1-3 */
  [SEG_CARGO + 1 * 5 + 4] = { 21, 264, 72, 78, 6, 16 }, /* cargo-1-4 */
  [SEG_CARGO + 2 * 5 + 0] = { 79, 281, 118, 137, 12, 11 }, /* cargo-2-0 */
  [SEG_CARGO + 2 * 5 + 1] = { 92, 281, 107, 137, 12, 11 }, /* cargo-2-1 */
  [SEG_CARGO + 2 * 5 + 2] = { 105, 281, 95, 137, 12, 11 }, /* cargo-2-2 */
  [SEG_CARGO + 2 * 5 + 3] = { 118, 281, 84, 137, 12, 11 }, /* cargo-2-3 */
  [SEG_CARGO + 2 * 5 + 4] = { 65, 281, 72, 137, 13, 11 }, /* cargo-2-4 */
  [SEG_CARGO + 3 * 5 + 0] = { 145, 264, 118, 164, 12, 14 }, /* cargo-3-0 */
  [SEG_CARGO + 3 * 5 + 1] = { 158, 264, 107, 164, 12, 14 }, /* cargo-3-1 */
  [SEG_CARGO + 3 * 5 + 2] = { 171, 264, 95, 164, 12, 14 }, /* cargo-3-2 */
  [SEG_CARGO + 3 * 5 + 3] = { 184, 264, 84, 164, 12, 14 }, /* cargo-3-3 */
  [SEG_CARGO + 3 * 5 + 4] = { 131, 264, 72, 164, 13, 14 }, /* cargo-3-4 */
  [SEG_COLON] = { 107, 296, 185, 166, 8, 3 }, /* colon */
  [SEG_DIGIT + 0 * 7 + 0] = { 49, 281, 195, 126, 3, 12 }, /* digit-0-a */
  [SEG_DIGIT + 0 * 7 + 1] = { 146, 281, 189, 136, 8, 5 }, /* digit-0-b */
  [SEG_DIGIT + 0 * 7 + 2] = { 155, 281, 181, 136, 8, 5 }, /* digit-0-c */
  [SEG_DIGIT + 0 * 7 + 3] = { 53, 281, 180, 126, 3, 12 }, /* digit-0-d */
  [SEG_DIGIT + 0 * 7 + 4] = { 36, 296, 181, 124, 8, 4 }, /* digit-0-e */
  [SEG_DIGIT + 0 * 7 + 5] = { 45, 296, 189, 124, 8, 4 }, /* digit-0-f */
  [SEG_DIGIT + 0 * 7 + 6] = { 39, 281, 187, 126, 4, 12 }, /* digit-0-g */
  [SEG_DIGIT + 1 * 7 + 0] = { 23, 281, 195, 146, 3, 13 }, /* digit-1-a */
  [SEG_DIGIT + 1 * 7 + 1] = { 54, 296, 189, 157, 8, 4 }, /* digit-1-b */
  [SEG_DIGIT + 1 * 7 + 2] = { 63, 296, 181, 157, 8, 4 }, /* digit-1-c */
  [SEG_DIGIT + 1 * 7 + 3] = { 27, 281, 180, 146, 3, 13 }, /* digit-1-d */
  [SEG_DIGIT + 1 * 7 + 4] = { 164, 281, 181, 144, 8, 5 }, /* digit-1-e */
  [SEG_DIGIT + 1 * 7 + 5] = { 173, 281, 189, 144, 8, 5 }, /* digit-1-f */
  [SEG_DIGIT + 1 * 7 + 6] = { 13, 281, 187, 146, 4, 13 }, /* digit-1-g */
  [SEG_DIGIT + 2 * 7 + 0] = { 57, 281, 195, 174, 3, 12 }, /* digit-2-a */
  [SEG_DIGIT + 2 * 7 + 1] = { 182, 281, 189, 184, 8, 5 }, /* digit-2-b */
  [SEG_DIGIT + 2 * 7 + 2] = { 191, 281, 181, 184, 8, 5 }, /* digit-2-c */
  [SEG_DIGIT + 2 * 7 + 3] = { 61, 281, 180, 174, 3, 12 }, /* digit-2-d */
  [SEG_DIGIT + 2 * 7 + 4] = { 0, 296, 181, 171, 8, 5 }, /* digit-2-e */
  [SEG_DIGIT + 2 * 7 + 5] = { 9, 296, 189, 171, 8, 5 }, /* digit-2-f */
  [SEG_DIGIT + 2 * 7 + 6] = { 44, 281, 187, 174, 4, 12 }, /* digit-2-g */
  [SEG_DIGIT + 3 * 7 + 0] = { 31, 281, 195, 194, 3, 13 }, /* digit-3-a */
  [SEG_DIGIT + 3 * 7 + 1] = { 72, 296, 189, 205, 8, 4 }, /* digit-3-b */
  [SEG_DIGIT + 3 * 7 + 2] = { 81, 296, 181, 205, 8, 4 }, /* digit-3-c */
  [SEG_DIGIT + 3 * 7 + 3] = { 35, 281, 180, 194, 3, 13 }, /* digit-3-d */
  [SEG_DIGIT + 3 * 7 + 4] = { 18, 296, 181, 192, 8, 5 }, /* digit-3-e */
  [SEG_DIGIT + 3 * 7 + 5] = { 27, 296, 189, 192, 8, 5 }, /* digit-3-f */
  [SEG_DIGIT + 3 * 7 + 6] = { 18, 281, 187, 194, 4, 13 }, /* digit-3-g */
  [SEG_GAME_A] = { 128, 236, 192, 6, 4, 26 }, /* game-a */
  [SEG_GAME_B] = { 133, 236, 183, 6, 4, 26 }, /* game-b */
  [SEG_GULL] = { 182, 236, 186, 77, 7, 22 }, /* gull */
  [SEG_HI] = { 141, 281, 189, 101, 4, 8 }, /* hi */
  [SEG_OLIVE_BELL + 0] = { 84, 236, 138, 11, 43, 26 }, /* olive-bell-0 */
  [SEG_OLIVE_BELL + 1] = { 100, 169, 138, 8, 43, 32 }, /* olive-bell-1 */
  [SEG_OLIVE_READY + 0] = { 0, 236, 138, 44, 41, 27 }, /* olive-ready-0 */
  [SEG_OLIVE_READY + 1] = { 117, 205, 138, 72, 41, 28 }, /* olive-ready-1 */
  [SEG_OLIVE_READY + 2] = { 159, 205, 138, 129, 41, 28 }, /* olive-ready-2 */
  [SEG_OLIVE_READY + 3] = { 42, 236, 138, 158, 41, 27 }, /* olive-ready-3 */
  [SEG_OLIVE_THROW + 0] = { 39, 205, 138, 43, 38, 29 }, /* olive-throw-0 */
  [SEG_OLIVE_THROW + 1] = { 144, 169, 138, 71, 38, 30 }, /* olive-throw-1 */
  [SEG_OLIVE_THROW + 2] = { 0, 205, 138, 128, 38, 30 }, /* olive-throw-2 */
  [SEG_OLIVE_THROW + 3] = { 78, 205, 138, 157, 38, 29 }, /* olive-throw-3 */
  [SEG_PM] = { 136, 281, 183, 213, 4, 10 }, /* pm */
  [SEG_POPEYE + 0] = { 0, 70, 31, 50, 42, 51 }, /* popeye-0 */
  [SEG_POPEYE + 1] = { 55, 122, 31, 78, 51, 41 }, /* popeye-1 */
  [SEG_POPEYE + 2] = { 0, 122, 31, 91, 54, 46 }, /* popeye-2 */
  [SEG_POPEYE + 3] = { 107, 122, 31, 110, 51, 41 }, /* popeye-3 */
  [SEG_POPEYE + 4] = { 43, 70, 31, 128, 42, 51 }, /* popeye-4 */
  [SEG_POPEYE_CATCH] = { 116, 264, 80, 108, 14, 14 }, /* popeye-catch */
  [SEG_POPEYE_DIZZY_LEFT] = { 0, 169, 31, 40, 49, 35 }, /* popeye-dizzy-left */
  [SEG_POPEYE_DIZZY_RIGHT] = { 50, 169, 31, 154, 49, 35 }, /* popeye-dizzy-right */
  [SEG_RING + 0] = { 54, 264, 0, 7, 12, 15 }, /* ring-0 */
  [SEG_RING + 1] = { 0, 281, 0, 26, 12, 14 }, /* ring-1 */
  [SEG_RING + 2] = { 67, 264, 0, 44, 12, 15 }, /* ring-2 */
  [SEG_RING_HALF] = { 94, 296, 0, 68, 12, 3 }, /* ring-half */
  [SEG_SPLASH + 0] = { 138, 236, 14, 47, 10, 23 }, /* splash-0 */
  [SEG_SPLASH + 1] = { 149, 236, 14, 76, 10, 23 }, /* splash-1 */
  [SEG_SPLASH + 2] = { 160, 236, 14, 133, 10, 23 }, /* splash-2 */
  [SEG_SPLASH + 3] = { 171, 236, 14, 161, 10, 23 }, /* splash-3 */
};

#endif
