/* Generated by tools/build_art.py from art/. Do not edit. */
#ifndef POPEYE_GW_SEGMENTS_H
#define POPEYE_GW_SEGMENTS_H

#include <stdint.h>

#include "scene.h"

/* Complete LCD inventory; every entry has black-on-transparent art. */
typedef struct {
  int16_t sheet_x, sheet_y, x, y, w, h;
} SegmentArt;

#define SEGMENT_ART_COUNT 82
#define SEGMENT_SHEET_WIDTH 200
#define SEGMENT_SHEET_HEIGHT 262

static const SegmentArt segment_art[SEG_COUNT] = {
  [SEG_AM] = { 96, 251, 186, 4, 9, 5 }, /* am */
  [SEG_BELL] = { 72, 259, 55, 3, 3, 3 }, /* bell */
  [SEG_BRUTUS + 0 * 3 + 0] = { 121, 176, 0, 134, 35, 39 }, /* brutus-left-idle */
  [SEG_BRUTUS + 0 * 3 + 2] = { 61, 176, 0, 134, 59, 39 }, /* brutus-left-strike */
  [SEG_BRUTUS + 0 * 3 + 1] = { 34, 122, 0, 121, 45, 52 }, /* brutus-left-windup */
  [SEG_BRUTUS + 1 * 3 + 0] = { 42, 0, 156, 97, 44, 59 }, /* brutus-right-idle */
  [SEG_BRUTUS + 1 * 3 + 2] = { 0, 176, 140, 109, 60, 47 }, /* brutus-right-strike */
  [SEG_BRUTUS + 1 * 3 + 1] = { 87, 0, 156, 97, 44, 59 }, /* brutus-right-windup */
  [SEG_CARGO + 0 * 5 + 0] = { 171, 176, 50, 70, 11, 14 }, /* cargo-0-0 */
  [SEG_CARGO + 0 * 5 + 1] = { 183, 176, 62, 59, 11, 14 }, /* cargo-0-1 */
  [SEG_CARGO + 0 * 5 + 2] = { 0, 224, 70, 75, 11, 14 }, /* cargo-0-2 */
  [SEG_CARGO + 0 * 5 + 3] = { 12, 224, 59, 104, 11, 14 }, /* cargo-0-3 */
  [SEG_CARGO + 0 * 5 + 4] = { 24, 224, 44, 130, 11, 14 }, /* cargo-0-4 */
  [SEG_CARGO + 1 * 5 + 0] = { 144, 239, 49, 77, 14, 7 }, /* cargo-1-0 */
  [SEG_CARGO + 1 * 5 + 1] = { 159, 239, 71, 61, 14, 7 }, /* cargo-1-1 */
  [SEG_CARGO + 1 * 5 + 2] = { 174, 239, 87, 80, 14, 7 }, /* cargo-1-2 */
  [SEG_CARGO + 1 * 5 + 3] = { 0, 251, 79, 110, 14, 7 }, /* cargo-1-3 */
  [SEG_CARGO + 1 * 5 + 4] = { 15, 251, 68, 137, 14, 7 }, /* cargo-1-4 */
  [SEG_CARGO + 2 * 5 + 0] = { 63, 224, 53, 72, 5, 12 }, /* cargo-2-0 */
  [SEG_CARGO + 2 * 5 + 1] = { 69, 224, 84, 51, 5, 12 }, /* cargo-2-1 */
  [SEG_CARGO + 2 * 5 + 2] = { 75, 224, 110, 71, 5, 12 }, /* cargo-2-2 */
  [SEG_CARGO + 2 * 5 + 3] = { 81, 224, 123, 102, 5, 12 }, /* cargo-2-3 */
  [SEG_CARGO + 2 * 5 + 4] = { 87, 224, 122, 132, 5, 12 }, /* cargo-2-4 */
  [SEG_CARGO + 3 * 5 + 0] = { 183, 224, 49, 73, 14, 11 }, /* cargo-3-0 */
  [SEG_CARGO + 3 * 5 + 1] = { 0, 239, 84, 49, 14, 11 }, /* cargo-3-1 */
  [SEG_CARGO + 3 * 5 + 2] = { 15, 239, 120, 66, 14, 11 }, /* cargo-3-2 */
  [SEG_CARGO + 3 * 5 + 3] = { 30, 239, 139, 99, 14, 11 }, /* cargo-3-3 */
  [SEG_CARGO + 3 * 5 + 4] = { 45, 239, 143, 133, 14, 11 }, /* cargo-3-4 */
  [SEG_COLON] = { 60, 239, 145, 7, 3, 10 }, /* colon */
  [SEG_DIGIT + 0 * 7 + 0] = { 172, 251, 110, 2, 11, 3 }, /* digit-0-a */
  [SEG_DIGIT + 0 * 7 + 1] = { 64, 239, 119, 3, 4, 9 }, /* digit-0-b */
  [SEG_DIGIT + 0 * 7 + 2] = { 69, 239, 119, 12, 4, 9 }, /* digit-0-c */
  [SEG_DIGIT + 0 * 7 + 3] = { 184, 251, 110, 19, 11, 3 }, /* digit-0-d */
  [SEG_DIGIT + 0 * 7 + 4] = { 74, 239, 108, 12, 4, 9 }, /* digit-0-e */
  [SEG_DIGIT + 0 * 7 + 5] = { 79, 239, 108, 3, 4, 9 }, /* digit-0-f */
  [SEG_DIGIT + 0 * 7 + 6] = { 124, 251, 110, 10, 11, 4 }, /* digit-0-g */
  [SEG_DIGIT + 1 * 7 + 0] = { 0, 259, 128, 2, 11, 3 }, /* digit-1-a */
  [SEG_DIGIT + 1 * 7 + 1] = { 84, 239, 137, 3, 4, 9 }, /* digit-1-b */
  [SEG_DIGIT + 1 * 7 + 2] = { 89, 239, 137, 12, 4, 9 }, /* digit-1-c */
  [SEG_DIGIT + 1 * 7 + 3] = { 12, 259, 128, 19, 11, 3 }, /* digit-1-d */
  [SEG_DIGIT + 1 * 7 + 4] = { 94, 239, 126, 12, 4, 9 }, /* digit-1-e */
  [SEG_DIGIT + 1 * 7 + 5] = { 99, 239, 126, 3, 4, 9 }, /* digit-1-f */
  [SEG_DIGIT + 1 * 7 + 6] = { 136, 251, 128, 10, 11, 4 }, /* digit-1-g */
  [SEG_DIGIT + 2 * 7 + 0] = { 24, 259, 152, 2, 11, 3 }, /* digit-2-a */
  [SEG_DIGIT + 2 * 7 + 1] = { 104, 239, 161, 3, 4, 9 }, /* digit-2-b */
  [SEG_DIGIT + 2 * 7 + 2] = { 109, 239, 161, 12, 4, 9 }, /* digit-2-c */
  [SEG_DIGIT + 2 * 7 + 3] = { 36, 259, 152, 19, 11, 3 }, /* digit-2-d */
  [SEG_DIGIT + 2 * 7 + 4] = { 114, 239, 150, 12, 4, 9 }, /* digit-2-e */
  [SEG_DIGIT + 2 * 7 + 5] = { 119, 239, 150, 3, 4, 9 }, /* digit-2-f */
  [SEG_DIGIT + 2 * 7 + 6] = { 148, 251, 152, 10, 11, 4 }, /* digit-2-g */
  [SEG_DIGIT + 3 * 7 + 0] = { 48, 259, 170, 2, 11, 3 }, /* digit-3-a */
  [SEG_DIGIT + 3 * 7 + 1] = { 124, 239, 179, 3, 4, 9 }, /* digit-3-b */
  [SEG_DIGIT + 3 * 7 + 2] = { 129, 239, 179, 12, 4, 9 }, /* digit-3-c */
  [SEG_DIGIT + 3 * 7 + 3] = { 60, 259, 170, 19, 11, 3 }, /* digit-3-d */
  [SEG_DIGIT + 3 * 7 + 4] = { 134, 239, 168, 12, 4, 9 }, /* digit-3-e */
  [SEG_DIGIT + 3 * 7 + 5] = { 139, 239, 168, 3, 4, 9 }, /* digit-3-f */
  [SEG_DIGIT + 3 * 7 + 6] = { 160, 251, 170, 10, 11, 4 }, /* digit-3-g */
  [SEG_GAME_A] = { 30, 251, 5, 4, 23, 5 }, /* game-a */
  [SEG_GAME_B] = { 54, 251, 5, 14, 23, 5 }, /* game-b */
  [SEG_HI] = { 116, 251, 80, 7, 7, 5 }, /* hi */
  [SEG_MISS + 0] = { 36, 224, 139, 30, 8, 12 }, /* miss-0 */
  [SEG_MISS + 1] = { 45, 224, 152, 30, 8, 12 }, /* miss-1 */
  [SEG_MISS + 2] = { 54, 224, 165, 30, 8, 12 }, /* miss-2 */
  [SEG_MISS_HALF] = { 93, 224, 178, 30, 5, 12 }, /* miss-half */
  [SEG_MISS_LABEL] = { 78, 251, 114, 35, 17, 5 }, /* miss-label */
  [SEG_OLIVE_BELL + 0] = { 129, 63, 26, 54, 26, 55 }, /* olive-bell-0 */
  [SEG_OLIVE_BELL + 1] = { 156, 63, 24, 55, 31, 54 }, /* olive-bell-1 */
  [SEG_OLIVE_READY] = { 37, 63, 24, 52, 29, 57 }, /* olive-ready */
  [SEG_OLIVE_THROW] = { 0, 122, 24, 56, 33, 53 }, /* olive-throw */
  [SEG_PM] = { 106, 251, 186, 14, 9, 5 }, /* pm */
  [SEG_POPEYE + 0] = { 80, 122, 43, 139, 45, 48 }, /* popeye-0 */
  [SEG_POPEYE + 1] = { 132, 0, 68, 129, 36, 58 }, /* popeye-1 */
  [SEG_POPEYE + 2] = { 0, 0, 79, 125, 41, 62 }, /* popeye-2 */
  [SEG_POPEYE + 3] = { 0, 63, 96, 129, 36, 58 }, /* popeye-3 */
  [SEG_POPEYE + 4] = { 126, 122, 112, 139, 45, 48 }, /* popeye-4 */
  [SEG_POPEYE_CATCH] = { 157, 176, 94, 120, 13, 16 }, /* popeye-catch */
  [SEG_POPEYE_DIZZY_LEFT] = { 67, 63, 35, 131, 30, 56 }, /* popeye-dizzy-left */
  [SEG_POPEYE_DIZZY_RIGHT] = { 98, 63, 135, 131, 30, 56 }, /* popeye-dizzy-right */
  [SEG_SPLASH + 0] = { 99, 224, 41, 200, 20, 11 }, /* splash-0 */
  [SEG_SPLASH + 1] = { 120, 224, 66, 200, 20, 11 }, /* splash-1 */
  [SEG_SPLASH + 2] = { 141, 224, 116, 200, 20, 11 }, /* splash-2 */
  [SEG_SPLASH + 3] = { 162, 224, 141, 200, 20, 11 }, /* splash-3 */
};

#endif
