/* Generated by tools/build_art.py from art/. Do not edit. */
#ifndef POPEYE_GW_SEGMENTS_LANDSCAPE_BOTTOM_H
#define POPEYE_GW_SEGMENTS_LANDSCAPE_BOTTOM_H

#include <stdint.h>

#include "segments.h"

/* Complete LCD inventory; every entry has black-on-transparent art. */

#define LANDSCAPE_BOTTOM_ART_COUNT 82
#define LANDSCAPE_BOTTOM_SHEET_WIDTH 200
#define LANDSCAPE_BOTTOM_SHEET_HEIGHT 273

static const SegmentArt landscape_bottom_art[SEG_COUNT] = {
  [SEG_AM] = { 65, 257, 12, 13, 5, 9 }, /* am */
  [SEG_BELL] = { 111, 269, 31, 14, 3, 3 }, /* bell */
  [SEG_BRUTUS + 0 * 3 + 0] = { 160, 121, 118, 188, 34, 40 }, /* brutus-left-idle */
  [SEG_BRUTUS + 0 * 3 + 2] = { 42, 0, 118, 160, 34, 68 }, /* brutus-left-strike */
  [SEG_BRUTUS + 0 * 3 + 1] = { 77, 0, 107, 176, 45, 52 }, /* brutus-left-windup */
  [SEG_BRUTUS + 1 * 3 + 0] = { 44, 69, 86, 0, 51, 50 }, /* brutus-right-idle */
  [SEG_BRUTUS + 1 * 3 + 2] = { 0, 0, 96, 0, 41, 68 }, /* brutus-right-strike */
  [SEG_BRUTUS + 1 * 3 + 1] = { 96, 69, 86, 0, 51, 50 }, /* brutus-right-windup */
  [SEG_CARGO + 0 * 5 + 0] = { 165, 240, 62, 158, 12, 13 }, /* cargo-0-0 */
  [SEG_CARGO + 0 * 5 + 1] = { 137, 240, 52, 144, 13, 13 }, /* cargo-0-1 */
  [SEG_CARGO + 0 * 5 + 2] = { 151, 240, 66, 135, 13, 13 }, /* cargo-0-2 */
  [SEG_CARGO + 0 * 5 + 3] = { 0, 257, 92, 148, 12, 11 }, /* cargo-0-3 */
  [SEG_CARGO + 0 * 5 + 4] = { 178, 240, 115, 165, 12, 12 }, /* cargo-0-4 */
  [SEG_CARGO + 1 * 5 + 0] = { 10, 240, 68, 156, 6, 16 }, /* cargo-1-0 */
  [SEG_CARGO + 1 * 5 + 1] = { 17, 240, 54, 131, 6, 16 }, /* cargo-1-1 */
  [SEG_CARGO + 1 * 5 + 2] = { 24, 240, 71, 112, 6, 16 }, /* cargo-1-2 */
  [SEG_CARGO + 1 * 5 + 3] = { 31, 240, 97, 121, 6, 16 }, /* cargo-1-3 */
  [SEG_CARGO + 1 * 5 + 4] = { 38, 240, 121, 134, 6, 16 }, /* cargo-1-4 */
  [SEG_CARGO + 2 * 5 + 0] = { 59, 240, 62, 157, 12, 15 }, /* cargo-2-0 */
  [SEG_CARGO + 2 * 5 + 1] = { 45, 240, 43, 121, 13, 15 }, /* cargo-2-1 */
  [SEG_CARGO + 2 * 5 + 2] = { 72, 240, 61, 92, 12, 15 }, /* cargo-2-2 */
  [SEG_CARGO + 2 * 5 + 3] = { 85, 240, 88, 77, 12, 15 }, /* cargo-2-3 */
  [SEG_CARGO + 2 * 5 + 4] = { 98, 240, 115, 78, 12, 15 }, /* cargo-2-4 */
  [SEG_CARGO + 3 * 5 + 0] = { 0, 240, 65, 156, 9, 16 }, /* cargo-3-0 */
  [SEG_CARGO + 3 * 5 + 1] = { 160, 206, 43, 116, 10, 16 }, /* cargo-3-1 */
  [SEG_CARGO + 3 * 5 + 2] = { 171, 206, 58, 75, 10, 16 }, /* cargo-3-2 */
  [SEG_CARGO + 3 * 5 + 3] = { 182, 206, 87, 53, 10, 16 }, /* cargo-3-3 */
  [SEG_CARGO + 3 * 5 + 4] = { 111, 240, 117, 49, 10, 15 }, /* cargo-3-4 */
  [SEG_COLON] = { 100, 269, 15, 60, 10, 3 }, /* colon */
  [SEG_DIGIT + 0 * 7 + 0] = { 33, 257, 10, 87, 3, 11 }, /* digit-0-a */
  [SEG_DIGIT + 0 * 7 + 1] = { 135, 257, 11, 85, 9, 4 }, /* digit-0-b */
  [SEG_DIGIT + 0 * 7 + 2] = { 145, 257, 20, 85, 9, 4 }, /* digit-0-c */
  [SEG_DIGIT + 0 * 7 + 3] = { 37, 257, 27, 87, 3, 11 }, /* digit-0-d */
  [SEG_DIGIT + 0 * 7 + 4] = { 155, 257, 20, 96, 9, 4 }, /* digit-0-e */
  [SEG_DIGIT + 0 * 7 + 5] = { 165, 257, 11, 96, 9, 4 }, /* digit-0-f */
  [SEG_DIGIT + 0 * 7 + 6] = { 13, 257, 18, 87, 4, 11 }, /* digit-0-g */
  [SEG_DIGIT + 1 * 7 + 0] = { 41, 257, 10, 69, 3, 11 }, /* digit-1-a */
  [SEG_DIGIT + 1 * 7 + 1] = { 175, 257, 11, 67, 9, 4 }, /* digit-1-b */
  [SEG_DIGIT + 1 * 7 + 2] = { 185, 257, 20, 67, 9, 4 }, /* digit-1-c */
  [SEG_DIGIT + 1 * 7 + 3] = { 45, 257, 27, 69, 3, 11 }, /* digit-1-d */
  [SEG_DIGIT + 1 * 7 + 4] = { 0, 269, 20, 78, 9, 4 }, /* digit-1-e */
  [SEG_DIGIT + 1 * 7 + 5] = { 10, 269, 11, 78, 9, 4 }, /* digit-1-f */
  [SEG_DIGIT + 1 * 7 + 6] = { 18, 257, 18, 69, 4, 11 }, /* digit-1-g */
  [SEG_DIGIT + 2 * 7 + 0] = { 49, 257, 10, 45, 3, 11 }, /* digit-2-a */
  [SEG_DIGIT + 2 * 7 + 1] = { 20, 269, 11, 43, 9, 4 }, /* digit-2-b */
  [SEG_DIGIT + 2 * 7 + 2] = { 30, 269, 20, 43, 9, 4 }, /* digit-2-c */
  [SEG_DIGIT + 2 * 7 + 3] = { 53, 257, 27, 45, 3, 11 }, /* digit-2-d */
  [SEG_DIGIT + 2 * 7 + 4] = { 40, 269, 20, 54, 9, 4 }, /* digit-2-e */
  [SEG_DIGIT + 2 * 7 + 5] = { 50, 269, 11, 54, 9, 4 }, /* digit-2-f */
  [SEG_DIGIT + 2 * 7 + 6] = { 23, 257, 18, 45, 4, 11 }, /* digit-2-g */
  [SEG_DIGIT + 3 * 7 + 0] = { 57, 257, 10, 27, 3, 11 }, /* digit-3-a */
  [SEG_DIGIT + 3 * 7 + 1] = { 60, 269, 11, 25, 9, 4 }, /* digit-3-b */
  [SEG_DIGIT + 3 * 7 + 2] = { 70, 269, 20, 25, 9, 4 }, /* digit-3-c */
  [SEG_DIGIT + 3 * 7 + 3] = { 61, 257, 27, 27, 3, 11 }, /* digit-3-d */
  [SEG_DIGIT + 3 * 7 + 4] = { 80, 269, 20, 36, 9, 4 }, /* digit-3-e */
  [SEG_DIGIT + 3 * 7 + 5] = { 90, 269, 11, 36, 9, 4 }, /* digit-3-f */
  [SEG_DIGIT + 3 * 7 + 6] = { 28, 257, 18, 27, 4, 11 }, /* digit-3-g */
  [SEG_GAME_A] = { 100, 206, 4, 196, 4, 26 }, /* game-a */
  [SEG_GAME_B] = { 105, 206, 13, 196, 4, 26 }, /* game-b */
  [SEG_HI] = { 116, 257, 9, 121, 5, 7 }, /* hi */
  [SEG_MISS + 0] = { 77, 257, 32, 61, 12, 8 }, /* miss-0 */
  [SEG_MISS + 1] = { 90, 257, 32, 48, 12, 8 }, /* miss-1 */
  [SEG_MISS + 2] = { 103, 257, 32, 35, 12, 8 }, /* miss-2 */
  [SEG_MISS_HALF] = { 122, 257, 32, 25, 12, 5 }, /* miss-half */
  [SEG_MISS_LABEL] = { 154, 206, 37, 77, 5, 17 }, /* miss-label */
  [SEG_OLIVE_BELL + 0] = { 51, 206, 48, 168, 48, 30 }, /* olive-bell-0 */
  [SEG_OLIVE_BELL + 1] = { 149, 168, 49, 165, 47, 35 }, /* olive-bell-1 */
  [SEG_OLIVE_READY] = { 0, 206, 46, 167, 50, 33 }, /* olive-ready */
  [SEG_OLIVE_THROW] = { 0, 168, 50, 163, 46, 37 }, /* olive-throw */
  [SEG_PM] = { 71, 257, 22, 13, 5, 9 }, /* pm */
  [SEG_POPEYE + 0] = { 123, 0, 122, 127, 43, 51 }, /* popeye-0 */
  [SEG_POPEYE + 1] = { 56, 121, 114, 109, 51, 41 }, /* popeye-1 */
  [SEG_POPEYE + 2] = { 0, 121, 110, 91, 55, 46 }, /* popeye-2 */
  [SEG_POPEYE + 3] = { 108, 121, 114, 77, 51, 41 }, /* popeye-3 */
  [SEG_POPEYE + 4] = { 0, 69, 122, 49, 43, 51 }, /* popeye-4 */
  [SEG_POPEYE_CATCH] = { 122, 240, 106, 106, 14, 14 }, /* popeye-catch */
  [SEG_POPEYE_DIZZY_LEFT] = { 47, 168, 115, 153, 50, 35 }, /* popeye-dizzy-left */
  [SEG_POPEYE_DIZZY_RIGHT] = { 98, 168, 115, 39, 50, 35 }, /* popeye-dizzy-right */
  [SEG_SPLASH + 0] = { 110, 206, 176, 158, 10, 23 }, /* splash-0 */
  [SEG_SPLASH + 1] = { 121, 206, 176, 129, 10, 23 }, /* splash-1 */
  [SEG_SPLASH + 2] = { 132, 206, 176, 72, 10, 23 }, /* splash-2 */
  [SEG_SPLASH + 3] = { 143, 206, 176, 44, 10, 23 }, /* splash-3 */
};

#endif
