/* Generated by tools/build_art.py from art/. Do not edit. */
#ifndef POPEYE_GW_SEGMENTS_LANDSCAPE_H
#define POPEYE_GW_SEGMENTS_LANDSCAPE_H

#include <stdint.h>

#include "segments.h"

/* Complete LCD inventory; every entry has black-on-transparent art. */

#define LANDSCAPE_ART_COUNT 82
#define LANDSCAPE_SHEET_WIDTH 200
#define LANDSCAPE_SHEET_HEIGHT 273

static const SegmentArt landscape_art[SEG_COUNT] = {
  [SEG_AM] = { 65, 257, 183, 206, 5, 9 }, /* am */
  [SEG_BELL] = { 111, 269, 166, 211, 3, 3 }, /* bell */
  [SEG_BRUTUS + 0 * 3 + 0] = { 160, 121, 48, 0, 34, 40 }, /* brutus-left-idle */
  [SEG_BRUTUS + 0 * 3 + 2] = { 42, 0, 48, 0, 34, 68 }, /* brutus-left-strike */
  [SEG_BRUTUS + 0 * 3 + 1] = { 77, 0, 48, 0, 45, 52 }, /* brutus-left-windup */
  [SEG_BRUTUS + 1 * 3 + 0] = { 44, 69, 63, 178, 51, 50 }, /* brutus-right-idle */
  [SEG_BRUTUS + 1 * 3 + 2] = { 0, 0, 63, 160, 41, 68 }, /* brutus-right-strike */
  [SEG_BRUTUS + 1 * 3 + 1] = { 96, 69, 63, 178, 51, 50 }, /* brutus-right-windup */
  [SEG_CARGO + 0 * 5 + 0] = { 165, 240, 126, 57, 12, 13 }, /* cargo-0-0 */
  [SEG_CARGO + 0 * 5 + 1] = { 137, 240, 135, 71, 13, 13 }, /* cargo-0-1 */
  [SEG_CARGO + 0 * 5 + 2] = { 151, 240, 121, 80, 13, 13 }, /* cargo-0-2 */
  [SEG_CARGO + 0 * 5 + 3] = { 0, 257, 96, 69, 12, 11 }, /* cargo-0-3 */
  [SEG_CARGO + 0 * 5 + 4] = { 178, 240, 73, 51, 12, 12 }, /* cargo-0-4 */
  [SEG_CARGO + 1 * 5 + 0] = { 10, 240, 126, 56, 6, 16 }, /* cargo-1-0 */
  [SEG_CARGO + 1 * 5 + 1] = { 17, 240, 140, 81, 6, 16 }, /* cargo-1-1 */
  [SEG_CARGO + 1 * 5 + 2] = { 24, 240, 123, 100, 6, 16 }, /* cargo-1-2 */
  [SEG_CARGO + 1 * 5 + 3] = { 31, 240, 97, 91, 6, 16 }, /* cargo-1-3 */
  [SEG_CARGO + 1 * 5 + 4] = { 38, 240, 73, 78, 6, 16 }, /* cargo-1-4 */
  [SEG_CARGO + 2 * 5 + 0] = { 59, 240, 126, 56, 12, 15 }, /* cargo-2-0 */
  [SEG_CARGO + 2 * 5 + 1] = { 45, 240, 144, 92, 13, 15 }, /* cargo-2-1 */
  [SEG_CARGO + 2 * 5 + 2] = { 72, 240, 127, 121, 12, 15 }, /* cargo-2-2 */
  [SEG_CARGO + 2 * 5 + 3] = { 85, 240, 100, 136, 12, 15 }, /* cargo-2-3 */
  [SEG_CARGO + 2 * 5 + 4] = { 98, 240, 73, 135, 12, 15 }, /* cargo-2-4 */
  [SEG_CARGO + 3 * 5 + 0] = { 0, 240, 126, 56, 9, 16 }, /* cargo-3-0 */
  [SEG_CARGO + 3 * 5 + 1] = { 160, 206, 147, 96, 10, 16 }, /* cargo-3-1 */
  [SEG_CARGO + 3 * 5 + 2] = { 171, 206, 132, 137, 10, 16 }, /* cargo-3-2 */
  [SEG_CARGO + 3 * 5 + 3] = { 182, 206, 103, 159, 10, 16 }, /* cargo-3-3 */
  [SEG_CARGO + 3 * 5 + 4] = { 111, 240, 73, 164, 10, 15 }, /* cargo-3-4 */
  [SEG_COLON] = { 100, 269, 175, 165, 10, 3 }, /* colon */
  [SEG_DIGIT + 0 * 7 + 0] = { 33, 257, 187, 130, 3, 11 }, /* digit-0-a */
  [SEG_DIGIT + 0 * 7 + 1] = { 135, 257, 180, 139, 9, 4 }, /* digit-0-b */
  [SEG_DIGIT + 0 * 7 + 2] = { 145, 257, 171, 139, 9, 4 }, /* digit-0-c */
  [SEG_DIGIT + 0 * 7 + 3] = { 37, 257, 170, 130, 3, 11 }, /* digit-0-d */
  [SEG_DIGIT + 0 * 7 + 4] = { 155, 257, 171, 128, 9, 4 }, /* digit-0-e */
  [SEG_DIGIT + 0 * 7 + 5] = { 165, 257, 180, 128, 9, 4 }, /* digit-0-f */
  [SEG_DIGIT + 0 * 7 + 6] = { 13, 257, 178, 130, 4, 11 }, /* digit-0-g */
  [SEG_DIGIT + 1 * 7 + 0] = { 41, 257, 187, 148, 3, 11 }, /* digit-1-a */
  [SEG_DIGIT + 1 * 7 + 1] = { 175, 257, 180, 157, 9, 4 }, /* digit-1-b */
  [SEG_DIGIT + 1 * 7 + 2] = { 185, 257, 171, 157, 9, 4 }, /* digit-1-c */
  [SEG_DIGIT + 1 * 7 + 3] = { 45, 257, 170, 148, 3, 11 }, /* digit-1-d */
  [SEG_DIGIT + 1 * 7 + 4] = { 0, 269, 171, 146, 9, 4 }, /* digit-1-e */
  [SEG_DIGIT + 1 * 7 + 5] = { 10, 269, 180, 146, 9, 4 }, /* digit-1-f */
  [SEG_DIGIT + 1 * 7 + 6] = { 18, 257, 178, 148, 4, 11 }, /* digit-1-g */
  [SEG_DIGIT + 2 * 7 + 0] = { 49, 257, 187, 172, 3, 11 }, /* digit-2-a */
  [SEG_DIGIT + 2 * 7 + 1] = { 20, 269, 180, 181, 9, 4 }, /* digit-2-b */
  [SEG_DIGIT + 2 * 7 + 2] = { 30, 269, 171, 181, 9, 4 }, /* digit-2-c */
  [SEG_DIGIT + 2 * 7 + 3] = { 53, 257, 170, 172, 3, 11 }, /* digit-2-d */
  [SEG_DIGIT + 2 * 7 + 4] = { 40, 269, 171, 170, 9, 4 }, /* digit-2-e */
  [SEG_DIGIT + 2 * 7 + 5] = { 50, 269, 180, 170, 9, 4 }, /* digit-2-f */
  [SEG_DIGIT + 2 * 7 + 6] = { 23, 257, 178, 172, 4, 11 }, /* digit-2-g */
  [SEG_DIGIT + 3 * 7 + 0] = { 57, 257, 187, 190, 3, 11 }, /* digit-3-a */
  [SEG_DIGIT + 3 * 7 + 1] = { 60, 269, 180, 199, 9, 4 }, /* digit-3-b */
  [SEG_DIGIT + 3 * 7 + 2] = { 70, 269, 171, 199, 9, 4 }, /* digit-3-c */
  [SEG_DIGIT + 3 * 7 + 3] = { 61, 257, 170, 190, 3, 11 }, /* digit-3-d */
  [SEG_DIGIT + 3 * 7 + 4] = { 80, 269, 171, 188, 9, 4 }, /* digit-3-e */
  [SEG_DIGIT + 3 * 7 + 5] = { 90, 269, 180, 188, 9, 4 }, /* digit-3-f */
  [SEG_DIGIT + 3 * 7 + 6] = { 28, 257, 178, 190, 4, 11 }, /* digit-3-g */
  [SEG_GAME_A] = { 100, 206, 192, 6, 4, 26 }, /* game-a */
  [SEG_GAME_B] = { 105, 206, 183, 6, 4, 26 }, /* game-b */
  [SEG_HI] = { 116, 257, 186, 100, 5, 7 }, /* hi */
  [SEG_MISS + 0] = { 77, 257, 156, 159, 12, 8 }, /* miss-0 */
  [SEG_MISS + 1] = { 90, 257, 156, 172, 12, 8 }, /* miss-1 */
  [SEG_MISS + 2] = { 103, 257, 156, 185, 12, 8 }, /* miss-2 */
  [SEG_MISS_HALF] = { 122, 257, 156, 198, 12, 5 }, /* miss-half */
  [SEG_MISS_LABEL] = { 154, 206, 158, 134, 5, 17 }, /* miss-label */
  [SEG_OLIVE_BELL + 0] = { 51, 206, 104, 30, 48, 30 }, /* olive-bell-0 */
  [SEG_OLIVE_BELL + 1] = { 149, 168, 104, 28, 47, 35 }, /* olive-bell-1 */
  [SEG_OLIVE_READY] = { 0, 206, 104, 28, 50, 33 }, /* olive-ready */
  [SEG_OLIVE_THROW] = { 0, 168, 104, 28, 46, 37 }, /* olive-throw */
  [SEG_PM] = { 71, 257, 173, 206, 5, 9 }, /* pm */
  [SEG_POPEYE + 0] = { 123, 0, 35, 50, 43, 51 }, /* popeye-0 */
  [SEG_POPEYE + 1] = { 56, 121, 35, 78, 51, 41 }, /* popeye-1 */
  [SEG_POPEYE + 2] = { 0, 121, 35, 91, 55, 46 }, /* popeye-2 */
  [SEG_POPEYE + 3] = { 108, 121, 35, 110, 51, 41 }, /* popeye-3 */
  [SEG_POPEYE + 4] = { 0, 69, 35, 128, 43, 51 }, /* popeye-4 */
  [SEG_POPEYE_CATCH] = { 122, 240, 80, 108, 14, 14 }, /* popeye-catch */
  [SEG_POPEYE_DIZZY_LEFT] = { 47, 168, 35, 40, 50, 35 }, /* popeye-dizzy-left */
  [SEG_POPEYE_DIZZY_RIGHT] = { 98, 168, 35, 154, 50, 35 }, /* popeye-dizzy-right */
  [SEG_SPLASH + 0] = { 110, 206, 14, 47, 10, 23 }, /* splash-0 */
  [SEG_SPLASH + 1] = { 121, 206, 14, 76, 10, 23 }, /* splash-1 */
  [SEG_SPLASH + 2] = { 132, 206, 14, 133, 10, 23 }, /* splash-2 */
  [SEG_SPLASH + 3] = { 143, 206, 14, 161, 10, 23 }, /* splash-3 */
};

#endif
