/* Generated by tools/build_art.py from art/. Do not edit. */
#ifndef POPEYE_GW_SEGMENTS_LANDSCAPE_BOTTOM_H
#define POPEYE_GW_SEGMENTS_LANDSCAPE_BOTTOM_H

#include <stdint.h>

#include "segments.h"

/* Complete LCD inventory; every entry has black-on-transparent art. */

#define LANDSCAPE_BOTTOM_ART_COUNT 89
#define LANDSCAPE_BOTTOM_SHEET_WIDTH 200
#define LANDSCAPE_BOTTOM_SHEET_HEIGHT 302

static const SegmentArt landscape_bottom_art[SEG_COUNT] = {
  [SEG_AM] = { 166, 273, 12, 13, 5, 9 }, /* am */
  [SEG_BELL] = { 51, 298, 31, 14, 3, 3 }, /* bell */
  [SEG_BRUTUS + 0 * 3 + 0] = { 52, 168, 118, 188, 34, 40 }, /* brutus-left-idle */
  [SEG_BRUTUS + 0 * 3 + 2] = { 42, 0, 118, 160, 34, 68 }, /* brutus-left-strike */
  [SEG_BRUTUS + 0 * 3 + 1] = { 77, 0, 107, 176, 45, 52 }, /* brutus-left-windup */
  [SEG_BRUTUS + 1 * 3 + 0] = { 44, 69, 86, 0, 51, 50 }, /* brutus-right-idle */
  [SEG_BRUTUS + 1 * 3 + 2] = { 0, 0, 96, 0, 41, 68 }, /* brutus-right-strike */
  [SEG_BRUTUS + 1 * 3 + 1] = { 96, 69, 86, 0, 51, 50 }, /* brutus-right-windup */
  [SEG_CARGO + 0 * 5 + 0] = { 67, 273, 62, 158, 12, 13 }, /* cargo-0-0 */
  [SEG_CARGO + 0 * 5 + 1] = { 39, 273, 52, 144, 13, 13 }, /* cargo-0-1 */
  [SEG_CARGO + 0 * 5 + 2] = { 53, 273, 66, 135, 13, 13 }, /* cargo-0-2 */
  [SEG_CARGO + 0 * 5 + 3] = { 93, 273, 92, 148, 12, 11 }, /* cargo-0-3 */
  [SEG_CARGO + 0 * 5 + 4] = { 80, 273, 115, 165, 12, 12 }, /* cargo-0-4 */
  [SEG_CARGO + 1 * 5 + 0] = { 103, 246, 68, 156, 6, 16 }, /* cargo-1-0 */
  [SEG_CARGO + 1 * 5 + 1] = { 110, 246, 54, 131, 6, 16 }, /* cargo-1-1 */
  [SEG_CARGO + 1 * 5 + 2] = { 117, 246, 71, 112, 6, 16 }, /* cargo-1-2 */
  [SEG_CARGO + 1 * 5 + 3] = { 124, 246, 97, 121, 6, 16 }, /* cargo-1-3 */
  [SEG_CARGO + 1 * 5 + 4] = { 131, 246, 121, 134, 6, 16 }, /* cargo-1-4 */
  [SEG_CARGO + 2 * 5 + 0] = { 152, 246, 62, 157, 12, 15 }, /* cargo-2-0 */
  [SEG_CARGO + 2 * 5 + 1] = { 138, 246, 43, 121, 13, 15 }, /* cargo-2-1 */
  [SEG_CARGO + 2 * 5 + 2] = { 165, 246, 61, 92, 12, 15 }, /* cargo-2-2 */
  [SEG_CARGO + 2 * 5 + 3] = { 178, 246, 88, 77, 12, 15 }, /* cargo-2-3 */
  [SEG_CARGO + 2 * 5 + 4] = { 0, 273, 115, 78, 12, 15 }, /* cargo-2-4 */
  [SEG_CARGO + 3 * 5 + 0] = { 93, 246, 65, 156, 9, 16 }, /* cargo-3-0 */
  [SEG_CARGO + 3 * 5 + 1] = { 60, 246, 43, 116, 10, 16 }, /* cargo-3-1 */
  [SEG_CARGO + 3 * 5 + 2] = { 71, 246, 58, 75, 10, 16 }, /* cargo-3-2 */
  [SEG_CARGO + 3 * 5 + 3] = { 82, 246, 87, 53, 10, 16 }, /* cargo-3-3 */
  [SEG_CARGO + 3 * 5 + 4] = { 13, 273, 117, 49, 10, 15 }, /* cargo-3-4 */
  [SEG_COLON] = { 40, 298, 15, 60, 10, 3 }, /* colon */
  [SEG_DIGIT + 0 * 7 + 0] = { 126, 273, 10, 87, 3, 11 }, /* digit-0-a */
  [SEG_DIGIT + 0 * 7 + 1] = { 76, 289, 11, 85, 9, 4 }, /* digit-0-b */
  [SEG_DIGIT + 0 * 7 + 2] = { 86, 289, 20, 85, 9, 4 }, /* digit-0-c */
  [SEG_DIGIT + 0 * 7 + 3] = { 130, 273, 27, 87, 3, 11 }, /* digit-0-d */
  [SEG_DIGIT + 0 * 7 + 4] = { 96, 289, 20, 96, 9, 4 }, /* digit-0-e */
  [SEG_DIGIT + 0 * 7 + 5] = { 106, 289, 11, 96, 9, 4 }, /* digit-0-f */
  [SEG_DIGIT + 0 * 7 + 6] = { 106, 273, 18, 87, 4, 11 }, /* digit-0-g */
  [SEG_DIGIT + 1 * 7 + 0] = { 134, 273, 10, 69, 3, 11 }, /* digit-1-a */
  [SEG_DIGIT + 1 * 7 + 1] = { 116, 289, 11, 67, 9, 4 }, /* digit-1-b */
  [SEG_DIGIT + 1 * 7 + 2] = { 126, 289, 20, 67, 9, 4 }, /* digit-1-c */
  [SEG_DIGIT + 1 * 7 + 3] = { 138, 273, 27, 69, 3, 11 }, /* digit-1-d */
  [SEG_DIGIT + 1 * 7 + 4] = { 136, 289, 20, 78, 9, 4 }, /* digit-1-e */
  [SEG_DIGIT + 1 * 7 + 5] = { 146, 289, 11, 78, 9, 4 }, /* digit-1-f */
  [SEG_DIGIT + 1 * 7 + 6] = { 111, 273, 18, 69, 4, 11 }, /* digit-1-g */
  [SEG_DIGIT + 2 * 7 + 0] = { 142, 273, 10, 45, 3, 11 }, /* digit-2-a */
  [SEG_DIGIT + 2 * 7 + 1] = { 156, 289, 11, 43, 9, 4 }, /* digit-2-b */
  [SEG_DIGIT + 2 * 7 + 2] = { 166, 289, 20, 43, 9, 4 }, /* digit-2-c */
  [SEG_DIGIT + 2 * 7 + 3] = { 146, 273, 27, 45, 3, 11 }, /* digit-2-d */
  [SEG_DIGIT + 2 * 7 + 4] = { 176, 289, 20, 54, 9, 4 }, /* digit-2-e */
  [SEG_DIGIT + 2 * 7 + 5] = { 186, 289, 11, 54, 9, 4 }, /* digit-2-f */
  [SEG_DIGIT + 2 * 7 + 6] = { 116, 273, 18, 45, 4, 11 }, /* digit-2-g */
  [SEG_DIGIT + 3 * 7 + 0] = { 150, 273, 10, 27, 3, 11 }, /* digit-3-a */
  [SEG_DIGIT + 3 * 7 + 1] = { 0, 298, 11, 25, 9, 4 }, /* digit-3-b */
  [SEG_DIGIT + 3 * 7 + 2] = { 10, 298, 20, 25, 9, 4 }, /* digit-3-c */
  [SEG_DIGIT + 3 * 7 + 3] = { 154, 273, 27, 27, 3, 11 }, /* digit-3-d */
  [SEG_DIGIT + 3 * 7 + 4] = { 20, 298, 20, 36, 9, 4 }, /* digit-3-e */
  [SEG_DIGIT + 3 * 7 + 5] = { 30, 298, 11, 36, 9, 4 }, /* digit-3-f */
  [SEG_DIGIT + 3 * 7 + 6] = { 121, 273, 18, 27, 4, 11 }, /* digit-3-g */
  [SEG_GAME_A] = { 0, 246, 4, 196, 4, 26 }, /* game-a */
  [SEG_GAME_B] = { 5, 246, 13, 196, 4, 26 }, /* game-b */
  [SEG_HEART + 0] = { 33, 289, 49, 155, 5, 8 }, /* heart-0 */
  [SEG_HEART + 1] = { 39, 289, 46, 141, 5, 8 }, /* heart-1 */
  [SEG_HEART + 2] = { 26, 289, 51, 127, 6, 8 }, /* heart-2 */
  [SEG_HEART + 3] = { 45, 289, 64, 117, 5, 8 }, /* heart-3 */
  [SEG_HEART + 4] = { 51, 289, 79, 110, 5, 8 }, /* heart-4 */
  [SEG_HI] = { 57, 289, 9, 121, 5, 7 }, /* hi */
  [SEG_MISS + 0] = { 178, 273, 32, 61, 12, 8 }, /* miss-0 */
  [SEG_MISS + 1] = { 0, 289, 32, 48, 12, 8 }, /* miss-1 */
  [SEG_MISS + 2] = { 13, 289, 32, 35, 12, 8 }, /* miss-2 */
  [SEG_MISS_HALF] = { 63, 289, 32, 25, 12, 5 }, /* miss-half */
  [SEG_MISS_LABEL] = { 54, 246, 37, 77, 5, 17 }, /* miss-label */
  [SEG_OLIVE_BELL + 0] = { 150, 210, 48, 168, 48, 30 }, /* olive-bell-0 */
  [SEG_OLIVE_BELL + 1] = { 51, 210, 49, 165, 47, 35 }, /* olive-bell-1 */
  [SEG_OLIVE_KISS] = { 56, 121, 48, 161, 48, 44 }, /* olive-kiss */
  [SEG_OLIVE_READY] = { 99, 210, 46, 167, 50, 33 }, /* olive-ready */
  [SEG_OLIVE_THROW] = { 87, 168, 50, 163, 46, 37 }, /* olive-throw */
  [SEG_PM] = { 172, 273, 22, 13, 5, 9 }, /* pm */
  [SEG_POPEYE + 0] = { 123, 0, 122, 127, 43, 51 }, /* popeye-0 */
  [SEG_POPEYE + 1] = { 105, 121, 114, 109, 51, 41 }, /* popeye-1 */
  [SEG_POPEYE + 2] = { 0, 121, 110, 91, 55, 46 }, /* popeye-2 */
  [SEG_POPEYE + 3] = { 0, 168, 114, 77, 51, 41 }, /* popeye-3 */
  [SEG_POPEYE + 4] = { 0, 69, 122, 49, 43, 51 }, /* popeye-4 */
  [SEG_POPEYE_CATCH] = { 24, 273, 106, 106, 14, 14 }, /* popeye-catch */
  [SEG_POPEYE_DIZZY_LEFT] = { 134, 168, 115, 153, 50, 35 }, /* popeye-dizzy-left */
  [SEG_POPEYE_DIZZY_RIGHT] = { 0, 210, 115, 39, 50, 35 }, /* popeye-dizzy-right */
  [SEG_POPEYE_HEART] = { 158, 273, 97, 108, 7, 10 }, /* popeye-heart */
  [SEG_SPLASH + 0] = { 10, 246, 176, 158, 10, 23 }, /* splash-0 */
  [SEG_SPLASH + 1] = { 21, 246, 176, 129, 10, 23 }, /* splash-1 */
  [SEG_SPLASH + 2] = { 32, 246, 176, 72, 10, 23 }, /* splash-2 */
  [SEG_SPLASH + 3] = { 43, 246, 176, 44, 10, 23 }, /* splash-3 */
};

#endif
