/* Generated by tools/build_art.py from art/. Do not edit. */
#ifndef POPEYE_GW_SEGMENTS_H
#define POPEYE_GW_SEGMENTS_H

#include <stdint.h>

#include "scene.h"

/* Complete LCD inventory; every entry has black-on-transparent art. */
typedef struct {
  int16_t sheet_x, sheet_y, x, y, w, h;
} SegmentArt;

#define SEGMENT_ART_COUNT 88
#define SEGMENT_SHEET_WIDTH 200
#define SEGMENT_SHEET_HEIGHT 307

static const SegmentArt segment_art[SEG_COUNT] = {
  [SEG_AM] = { 123, 296, 186, 4, 9, 5 }, /* am */
  [SEG_BELL] = { 96, 304, 55, 3, 3, 3 }, /* bell */
  [SEG_BRUTUS + 0 * 3 + 0] = { 42, 0, 0, 95, 44, 59 }, /* brutus-left-idle */
  [SEG_BRUTUS + 0 * 3 + 2] = { 0, 173, 0, 107, 60, 47 }, /* brutus-left-strike */
  [SEG_BRUTUS + 0 * 3 + 1] = { 87, 0, 0, 95, 44, 59 }, /* brutus-left-windup */
  [SEG_BRUTUS + 1 * 3 + 0] = { 132, 0, 156, 95, 44, 59 }, /* brutus-right-idle */
  [SEG_BRUTUS + 1 * 3 + 2] = { 61, 173, 140, 107, 60, 47 }, /* brutus-right-strike */
  [SEG_BRUTUS + 1 * 3 + 1] = { 0, 63, 156, 95, 44, 59 }, /* brutus-right-windup */
  [SEG_CARGO + 0 * 5 + 0] = { 78, 269, 43, 80, 14, 13 }, /* cargo-0-0 */
  [SEG_CARGO + 0 * 5 + 1] = { 93, 269, 43, 93, 14, 13 }, /* cargo-0-1 */
  [SEG_CARGO + 0 * 5 + 2] = { 108, 269, 43, 106, 14, 13 }, /* cargo-0-2 */
  [SEG_CARGO + 0 * 5 + 3] = { 123, 269, 43, 119, 14, 13 }, /* cargo-0-3 */
  [SEG_CARGO + 0 * 5 + 4] = { 138, 269, 43, 132, 14, 13 }, /* cargo-0-4 */
  [SEG_CARGO + 1 * 5 + 0] = { 0, 296, 68, 86, 14, 7 }, /* cargo-1-0 */
  [SEG_CARGO + 1 * 5 + 1] = { 15, 296, 68, 99, 14, 7 }, /* cargo-1-1 */
  [SEG_CARGO + 1 * 5 + 2] = { 30, 296, 68, 112, 14, 7 }, /* cargo-1-2 */
  [SEG_CARGO + 1 * 5 + 3] = { 45, 296, 68, 125, 14, 7 }, /* cargo-1-3 */
  [SEG_CARGO + 1 * 5 + 4] = { 60, 296, 68, 138, 14, 7 }, /* cargo-1-4 */
  [SEG_CARGO + 2 * 5 + 0] = { 28, 269, 120, 79, 9, 14 }, /* cargo-2-0 */
  [SEG_CARGO + 2 * 5 + 1] = { 38, 269, 120, 92, 9, 14 }, /* cargo-2-1 */
  [SEG_CARGO + 2 * 5 + 2] = { 48, 269, 120, 105, 9, 14 }, /* cargo-2-2 */
  [SEG_CARGO + 2 * 5 + 3] = { 58, 269, 120, 118, 9, 14 }, /* cargo-2-3 */
  [SEG_CARGO + 2 * 5 + 4] = { 68, 269, 120, 131, 9, 14 }, /* cargo-2-4 */
  [SEG_CARGO + 3 * 5 + 0] = { 151, 221, 143, 79, 13, 14 }, /* cargo-3-0 */
  [SEG_CARGO + 3 * 5 + 1] = { 165, 221, 143, 92, 13, 14 }, /* cargo-3-1 */
  [SEG_CARGO + 3 * 5 + 2] = { 179, 221, 143, 105, 13, 14 }, /* cargo-3-2 */
  [SEG_CARGO + 3 * 5 + 3] = { 0, 269, 143, 118, 13, 14 }, /* cargo-3-3 */
  [SEG_CARGO + 3 * 5 + 4] = { 14, 269, 143, 131, 13, 14 }, /* cargo-3-4 */
  [SEG_COLON] = { 84, 284, 145, 7, 3, 10 }, /* colon */
  [SEG_DIGIT + 0 * 7 + 0] = { 0, 304, 110, 2, 11, 3 }, /* digit-0-a */
  [SEG_DIGIT + 0 * 7 + 1] = { 88, 284, 119, 3, 4, 9 }, /* digit-0-b */
  [SEG_DIGIT + 0 * 7 + 2] = { 93, 284, 119, 12, 4, 9 }, /* digit-0-c */
  [SEG_DIGIT + 0 * 7 + 3] = { 12, 304, 110, 19, 11, 3 }, /* digit-0-d */
  [SEG_DIGIT + 0 * 7 + 4] = { 98, 284, 108, 12, 4, 9 }, /* digit-0-e */
  [SEG_DIGIT + 0 * 7 + 5] = { 103, 284, 108, 3, 4, 9 }, /* digit-0-f */
  [SEG_DIGIT + 0 * 7 + 6] = { 151, 296, 110, 10, 11, 4 }, /* digit-0-g */
  [SEG_DIGIT + 1 * 7 + 0] = { 24, 304, 128, 2, 11, 3 }, /* digit-1-a */
  [SEG_DIGIT + 1 * 7 + 1] = { 108, 284, 137, 3, 4, 9 }, /* digit-1-b */
  [SEG_DIGIT + 1 * 7 + 2] = { 113, 284, 137, 12, 4, 9 }, /* digit-1-c */
  [SEG_DIGIT + 1 * 7 + 3] = { 36, 304, 128, 19, 11, 3 }, /* digit-1-d */
  [SEG_DIGIT + 1 * 7 + 4] = { 118, 284, 126, 12, 4, 9 }, /* digit-1-e */
  [SEG_DIGIT + 1 * 7 + 5] = { 123, 284, 126, 3, 4, 9 }, /* digit-1-f */
  [SEG_DIGIT + 1 * 7 + 6] = { 163, 296, 128, 10, 11, 4 }, /* digit-1-g */
  [SEG_DIGIT + 2 * 7 + 0] = { 48, 304, 152, 2, 11, 3 }, /* digit-2-a */
  [SEG_DIGIT + 2 * 7 + 1] = { 128, 284, 161, 3, 4, 9 }, /* digit-2-b */
  [SEG_DIGIT + 2 * 7 + 2] = { 133, 284, 161, 12, 4, 9 }, /* digit-2-c */
  [SEG_DIGIT + 2 * 7 + 3] = { 60, 304, 152, 19, 11, 3 }, /* digit-2-d */
  [SEG_DIGIT + 2 * 7 + 4] = { 138, 284, 150, 12, 4, 9 }, /* digit-2-e */
  [SEG_DIGIT + 2 * 7 + 5] = { 143, 284, 150, 3, 4, 9 }, /* digit-2-f */
  [SEG_DIGIT + 2 * 7 + 6] = { 175, 296, 152, 10, 11, 4 }, /* digit-2-g */
  [SEG_DIGIT + 3 * 7 + 0] = { 72, 304, 170, 2, 11, 3 }, /* digit-3-a */
  [SEG_DIGIT + 3 * 7 + 1] = { 148, 284, 179, 3, 4, 9 }, /* digit-3-b */
  [SEG_DIGIT + 3 * 7 + 2] = { 153, 284, 179, 12, 4, 9 }, /* digit-3-c */
  [SEG_DIGIT + 3 * 7 + 3] = { 84, 304, 170, 19, 11, 3 }, /* digit-3-d */
  [SEG_DIGIT + 3 * 7 + 4] = { 158, 284, 168, 12, 4, 9 }, /* digit-3-e */
  [SEG_DIGIT + 3 * 7 + 5] = { 163, 284, 168, 3, 4, 9 }, /* digit-3-f */
  [SEG_DIGIT + 3 * 7 + 6] = { 187, 296, 170, 10, 11, 4 }, /* digit-3-g */
  [SEG_GAME_A] = { 75, 296, 5, 4, 23, 5 }, /* game-a */
  [SEG_GAME_B] = { 99, 296, 5, 14, 23, 5 }, /* game-b */
  [SEG_GULL] = { 168, 284, 67, 7, 19, 8 }, /* gull */
  [SEG_HI] = { 143, 296, 88, 7, 7, 5 }, /* hi */
  [SEG_OLIVE_BELL + 0] = { 29, 123, 9, 21, 23, 49 }, /* olive-bell-0 */
  [SEG_OLIVE_BELL + 1] = { 0, 123, 7, 21, 28, 49 }, /* olive-bell-1 */
  [SEG_OLIVE_READY + 0] = { 122, 173, 38, 23, 24, 47 }, /* olive-ready-0 */
  [SEG_OLIVE_READY + 1] = { 147, 173, 63, 23, 24, 47 }, /* olive-ready-1 */
  [SEG_OLIVE_READY + 2] = { 172, 173, 113, 23, 24, 47 }, /* olive-ready-2 */
  [SEG_OLIVE_READY + 3] = { 0, 221, 138, 23, 24, 47 }, /* olive-ready-3 */
  [SEG_OLIVE_THROW + 0] = { 25, 221, 37, 27, 27, 43 }, /* olive-throw-0 */
  [SEG_OLIVE_THROW + 1] = { 53, 221, 62, 27, 27, 43 }, /* olive-throw-1 */
  [SEG_OLIVE_THROW + 2] = { 81, 221, 112, 27, 27, 43 }, /* olive-throw-2 */
  [SEG_OLIVE_THROW + 3] = { 109, 221, 137, 27, 27, 43 }, /* olive-throw-3 */
  [SEG_PM] = { 133, 296, 186, 14, 9, 5 }, /* pm */
  [SEG_POPEYE + 0] = { 53, 123, 43, 144, 45, 48 }, /* popeye-0 */
  [SEG_POPEYE + 1] = { 45, 63, 68, 134, 36, 58 }, /* popeye-1 */
  [SEG_POPEYE + 2] = { 0, 0, 79, 130, 41, 62 }, /* popeye-2 */
  [SEG_POPEYE + 3] = { 82, 63, 96, 134, 36, 58 }, /* popeye-3 */
  [SEG_POPEYE + 4] = { 99, 123, 112, 144, 45, 48 }, /* popeye-4 */
  [SEG_POPEYE_CATCH] = { 137, 221, 94, 120, 13, 16 }, /* popeye-catch */
  [SEG_POPEYE_DIZZY_LEFT] = { 119, 63, 35, 136, 30, 56 }, /* popeye-dizzy-left */
  [SEG_POPEYE_DIZZY_RIGHT] = { 150, 63, 135, 136, 30, 56 }, /* popeye-dizzy-right */
  [SEG_RING + 0] = { 153, 269, 6, 214, 13, 13 }, /* ring-0 */
  [SEG_RING + 1] = { 167, 269, 22, 214, 13, 13 }, /* ring-1 */
  [SEG_RING + 2] = { 181, 269, 38, 214, 13, 13 }, /* ring-2 */
  [SEG_RING_HALF] = { 195, 269, 59, 214, 3, 13 }, /* ring-half */
  [SEG_SPLASH + 0] = { 0, 284, 41, 200, 20, 11 }, /* splash-0 */
  [SEG_SPLASH + 1] = { 21, 284, 66, 200, 20, 11 }, /* splash-1 */
  [SEG_SPLASH + 2] = { 42, 284, 116, 200, 20, 11 }, /* splash-2 */
  [SEG_SPLASH + 3] = { 63, 284, 141, 200, 20, 11 }, /* splash-3 */
};

#endif
