/* Generated by tools/build_art.py from art/. Do not edit. */
#ifndef POPEYE_GW_SEGMENTS_LANDSCAPE_H
#define POPEYE_GW_SEGMENTS_LANDSCAPE_H

#include <stdint.h>

#include "segments.h"

/* Complete LCD inventory; every entry has black-on-transparent art. */

#define LANDSCAPE_ART_COUNT 89
#define LANDSCAPE_SHEET_WIDTH 200
#define LANDSCAPE_SHEET_HEIGHT 302

static const SegmentArt landscape_art[SEG_COUNT] = {
  [SEG_AM] = { 166, 273, 183, 206, 5, 9 }, /* am */
  [SEG_BELL] = { 51, 298, 166, 211, 3, 3 }, /* bell */
  [SEG_BRUTUS + 0 * 3 + 0] = { 52, 168, 48, 0, 34, 40 }, /* brutus-left-idle */
  [SEG_BRUTUS + 0 * 3 + 2] = { 42, 0, 48, 0, 34, 68 }, /* brutus-left-strike */
  [SEG_BRUTUS + 0 * 3 + 1] = { 77, 0, 48, 0, 45, 52 }, /* brutus-left-windup */
  [SEG_BRUTUS + 1 * 3 + 0] = { 44, 69, 63, 178, 51, 50 }, /* brutus-right-idle */
  [SEG_BRUTUS + 1 * 3 + 2] = { 0, 0, 63, 160, 41, 68 }, /* brutus-right-strike */
  [SEG_BRUTUS + 1 * 3 + 1] = { 96, 69, 63, 178, 51, 50 }, /* brutus-right-windup */
  [SEG_CARGO + 0 * 5 + 0] = { 67, 273, 126, 57, 12, 13 }, /* cargo-0-0 */
  [SEG_CARGO + 0 * 5 + 1] = { 39, 273, 135, 71, 13, 13 }, /* cargo-0-1 */
  [SEG_CARGO + 0 * 5 + 2] = { 53, 273, 121, 80, 13, 13 }, /* cargo-0-2 */
  [SEG_CARGO + 0 * 5 + 3] = { 93, 273, 96, 69, 12, 11 }, /* cargo-0-3 */
  [SEG_CARGO + 0 * 5 + 4] = { 80, 273, 73, 51, 12, 12 }, /* cargo-0-4 */
  [SEG_CARGO + 1 * 5 + 0] = { 103, 246, 126, 56, 6, 16 }, /* cargo-1-0 */
  [SEG_CARGO + 1 * 5 + 1] = { 110, 246, 140, 81, 6, 16 }, /* cargo-1-1 */
  [SEG_CARGO + 1 * 5 + 2] = { 117, 246, 123, 100, 6, 16 }, /* cargo-1-2 */
  [SEG_CARGO + 1 * 5 + 3] = { 124, 246, 97, 91, 6, 16 }, /* cargo-1-3 */
  [SEG_CARGO + 1 * 5 + 4] = { 131, 246, 73, 78, 6, 16 }, /* cargo-1-4 */
  [SEG_CARGO + 2 * 5 + 0] = { 152, 246, 126, 56, 12, 15 }, /* cargo-2-0 */
  [SEG_CARGO + 2 * 5 + 1] = { 138, 246, 144, 92, 13, 15 }, /* cargo-2-1 */
  [SEG_CARGO + 2 * 5 + 2] = { 165, 246, 127, 121, 12, 15 }, /* cargo-2-2 */
  [SEG_CARGO + 2 * 5 + 3] = { 178, 246, 100, 136, 12, 15 }, /* cargo-2-3 */
  [SEG_CARGO + 2 * 5 + 4] = { 0, 273, 73, 135, 12, 15 }, /* cargo-2-4 */
  [SEG_CARGO + 3 * 5 + 0] = { 93, 246, 126, 56, 9, 16 }, /* cargo-3-0 */
  [SEG_CARGO + 3 * 5 + 1] = { 60, 246, 147, 96, 10, 16 }, /* cargo-3-1 */
  [SEG_CARGO + 3 * 5 + 2] = { 71, 246, 132, 137, 10, 16 }, /* cargo-3-2 */
  [SEG_CARGO + 3 * 5 + 3] = { 82, 246, 103, 159, 10, 16 }, /* cargo-3-3 */
  [SEG_CARGO + 3 * 5 + 4] = { 13, 273, 73, 164, 10, 15 }, /* cargo-3-4 */
  [SEG_COLON] = { 40, 298, 175, 165, 10, 3 }, /* colon */
  [SEG_DIGIT + 0 * 7 + 0] = { 126, 273, 187, 130, 3, 11 }, /* digit-0-a */
  [SEG_DIGIT + 0 * 7 + 1] = { 76, 289, 180, 139, 9, 4 }, /* digit-0-b */
  [SEG_DIGIT + 0 * 7 + 2] = { 86, 289, 171, 139, 9, 4 }, /* digit-0-c */
  [SEG_DIGIT + 0 * 7 + 3] = { 130, 273, 170, 130, 3, 11 }, /* digit-0-d */
  [SEG_DIGIT + 0 * 7 + 4] = { 96, 289, 171, 128, 9, 4 }, /* digit-0-e */
  [SEG_DIGIT + 0 * 7 + 5] = { 106, 289, 180, 128, 9, 4 }, /* digit-0-f */
  [SEG_DIGIT + 0 * 7 + 6] = { 106, 273, 178, 130, 4, 11 }, /* digit-0-g */
  [SEG_DIGIT + 1 * 7 + 0] = { 134, 273, 187, 148, 3, 11 }, /* digit-1-a */
  [SEG_DIGIT + 1 * 7 + 1] = { 116, 289, 180, 157, 9, 4 }, /* digit-1-b */
  [SEG_DIGIT + 1 * 7 + 2] = { 126, 289, 171, 157, 9, 4 }, /* digit-1-c */
  [SEG_DIGIT + 1 * 7 + 3] = { 138, 273, 170, 148, 3, 11 }, /* digit-1-d */
  [SEG_DIGIT + 1 * 7 + 4] = { 136, 289, 171, 146, 9, 4 }, /* digit-1-e */
  [SEG_DIGIT + 1 * 7 + 5] = { 146, 289, 180, 146, 9, 4 }, /* digit-1-f */
  [SEG_DIGIT + 1 * 7 + 6] = { 111, 273, 178, 148, 4, 11 }, /* digit-1-g */
  [SEG_DIGIT + 2 * 7 + 0] = { 142, 273, 187, 172, 3, 11 }, /* digit-2-a */
  [SEG_DIGIT + 2 * 7 + 1] = { 156, 289, 180, 181, 9, 4 }, /* digit-2-b */
  [SEG_DIGIT + 2 * 7 + 2] = { 166, 289, 171, 181, 9, 4 }, /* digit-2-c */
  [SEG_DIGIT + 2 * 7 + 3] = { 146, 273, 170, 172, 3, 11 }, /* digit-2-d */
  [SEG_DIGIT + 2 * 7 + 4] = { 176, 289, 171, 170, 9, 4 }, /* digit-2-e */
  [SEG_DIGIT + 2 * 7 + 5] = { 186, 289, 180, 170, 9, 4 }, /* digit-2-f */
  [SEG_DIGIT + 2 * 7 + 6] = { 116, 273, 178, 172, 4, 11 }, /* digit-2-g */
  [SEG_DIGIT + 3 * 7 + 0] = { 150, 273, 187, 190, 3, 11 }, /* digit-3-a */
  [SEG_DIGIT + 3 * 7 + 1] = { 0, 298, 180, 199, 9, 4 }, /* digit-3-b */
  [SEG_DIGIT + 3 * 7 + 2] = { 10, 298, 171, 199, 9, 4 }, /* digit-3-c */
  [SEG_DIGIT + 3 * 7 + 3] = { 154, 273, 170, 190, 3, 11 }, /* digit-3-d */
  [SEG_DIGIT + 3 * 7 + 4] = { 20, 298, 171, 188, 9, 4 }, /* digit-3-e */
  [SEG_DIGIT + 3 * 7 + 5] = { 30, 298, 180, 188, 9, 4 }, /* digit-3-f */
  [SEG_DIGIT + 3 * 7 + 6] = { 121, 273, 178, 190, 4, 11 }, /* digit-3-g */
  [SEG_GAME_A] = { 0, 246, 192, 6, 4, 26 }, /* game-a */
  [SEG_GAME_B] = { 5, 246, 183, 6, 4, 26 }, /* game-b */
  [SEG_HEART + 0] = { 33, 289, 146, 65, 5, 8 }, /* heart-0 */
  [SEG_HEART + 1] = { 39, 289, 149, 79, 5, 8 }, /* heart-1 */
  [SEG_HEART + 2] = { 26, 289, 143, 93, 6, 8 }, /* heart-2 */
  [SEG_HEART + 3] = { 45, 289, 131, 103, 5, 8 }, /* heart-3 */
  [SEG_HEART + 4] = { 51, 289, 116, 110, 5, 8 }, /* heart-4 */
  [SEG_HI] = { 57, 289, 186, 100, 5, 7 }, /* hi */
  [SEG_MISS + 0] = { 178, 273, 156, 159, 12, 8 }, /* miss-0 */
  [SEG_MISS + 1] = { 0, 289, 156, 172, 12, 8 }, /* miss-1 */
  [SEG_MISS + 2] = { 13, 289, 156, 185, 12, 8 }, /* miss-2 */
  [SEG_MISS_HALF] = { 63, 289, 156, 198, 12, 5 }, /* miss-half */
  [SEG_MISS_LABEL] = { 54, 246, 158, 134, 5, 17 }, /* miss-label */
  [SEG_OLIVE_BELL + 0] = { 150, 210, 104, 30, 48, 30 }, /* olive-bell-0 */
  [SEG_OLIVE_BELL + 1] = { 51, 210, 104, 28, 47, 35 }, /* olive-bell-1 */
  [SEG_OLIVE_KISS] = { 56, 121, 104, 23, 48, 44 }, /* olive-kiss */
  [SEG_OLIVE_READY] = { 99, 210, 104, 28, 50, 33 }, /* olive-ready */
  [SEG_OLIVE_THROW] = { 87, 168, 104, 28, 46, 37 }, /* olive-throw */
  [SEG_PM] = { 172, 273, 173, 206, 5, 9 }, /* pm */
  [SEG_POPEYE + 0] = { 123, 0, 35, 50, 43, 51 }, /* popeye-0 */
  [SEG_POPEYE + 1] = { 105, 121, 35, 78, 51, 41 }, /* popeye-1 */
  [SEG_POPEYE + 2] = { 0, 121, 35, 91, 55, 46 }, /* popeye-2 */
  [SEG_POPEYE + 3] = { 0, 168, 35, 110, 51, 41 }, /* popeye-3 */
  [SEG_POPEYE + 4] = { 0, 69, 35, 128, 43, 51 }, /* popeye-4 */
  [SEG_POPEYE_CATCH] = { 24, 273, 80, 108, 14, 14 }, /* popeye-catch */
  [SEG_POPEYE_DIZZY_LEFT] = { 134, 168, 35, 40, 50, 35 }, /* popeye-dizzy-left */
  [SEG_POPEYE_DIZZY_RIGHT] = { 0, 210, 35, 154, 50, 35 }, /* popeye-dizzy-right */
  [SEG_POPEYE_HEART] = { 158, 273, 96, 110, 7, 10 }, /* popeye-heart */
  [SEG_SPLASH + 0] = { 10, 246, 14, 47, 10, 23 }, /* splash-0 */
  [SEG_SPLASH + 1] = { 21, 246, 14, 76, 10, 23 }, /* splash-1 */
  [SEG_SPLASH + 2] = { 32, 246, 14, 133, 10, 23 }, /* splash-2 */
  [SEG_SPLASH + 3] = { 43, 246, 14, 161, 10, 23 }, /* splash-3 */
};

#endif
