/* Generated by tools/build_art.py from art/. Do not edit. */
#ifndef POPEYE_GW_SEGMENTS_H
#define POPEYE_GW_SEGMENTS_H

#include <stdint.h>

#include "scene.h"

/* Complete LCD inventory; every entry has black-on-transparent art. */
typedef struct {
  int16_t sheet_x, sheet_y, x, y, w, h;
} SegmentArt;

#define SEGMENT_ART_COUNT 82
#define SEGMENT_SHEET_WIDTH 200
#define SEGMENT_SHEET_HEIGHT 263

static const SegmentArt segment_art[SEG_COUNT] = {
  [SEG_AM] = { 126, 251, 186, 10, 9, 5 }, /* am */
  [SEG_BELL] = { 108, 259, 191, 29, 3, 3 }, /* bell */
  [SEG_BRUTUS + 0 * 3 + 0] = { 121, 176, 0, 134, 35, 39 }, /* brutus-left-idle */
  [SEG_BRUTUS + 0 * 3 + 2] = { 61, 176, 0, 134, 59, 39 }, /* brutus-left-strike */
  [SEG_BRUTUS + 0 * 3 + 1] = { 34, 122, 0, 121, 45, 52 }, /* brutus-left-windup */
  [SEG_BRUTUS + 1 * 3 + 0] = { 42, 0, 156, 97, 44, 59 }, /* brutus-right-idle */
  [SEG_BRUTUS + 1 * 3 + 2] = { 0, 176, 140, 109, 60, 47 }, /* brutus-right-strike */
  [SEG_BRUTUS + 1 * 3 + 1] = { 87, 0, 156, 97, 44, 59 }, /* brutus-right-windup */
  [SEG_CARGO + 0 * 5 + 0] = { 42, 224, 50, 70, 11, 14 }, /* cargo-0-0 */
  [SEG_CARGO + 0 * 5 + 1] = { 54, 224, 62, 59, 11, 14 }, /* cargo-0-1 */
  [SEG_CARGO + 0 * 5 + 2] = { 66, 224, 70, 75, 11, 14 }, /* cargo-0-2 */
  [SEG_CARGO + 0 * 5 + 3] = { 78, 224, 59, 104, 11, 14 }, /* cargo-0-3 */
  [SEG_CARGO + 0 * 5 + 4] = { 90, 224, 44, 130, 11, 14 }, /* cargo-0-4 */
  [SEG_CARGO + 1 * 5 + 0] = { 180, 239, 49, 77, 14, 7 }, /* cargo-1-0 */
  [SEG_CARGO + 1 * 5 + 1] = { 0, 251, 71, 61, 14, 7 }, /* cargo-1-1 */
  [SEG_CARGO + 1 * 5 + 2] = { 15, 251, 87, 80, 14, 7 }, /* cargo-1-2 */
  [SEG_CARGO + 1 * 5 + 3] = { 30, 251, 79, 110, 14, 7 }, /* cargo-1-3 */
  [SEG_CARGO + 1 * 5 + 4] = { 45, 251, 68, 137, 14, 7 }, /* cargo-1-4 */
  [SEG_CARGO + 2 * 5 + 0] = { 171, 176, 49, 70, 13, 14 }, /* cargo-2-0 */
  [SEG_CARGO + 2 * 5 + 1] = { 185, 176, 80, 49, 13, 14 }, /* cargo-2-1 */
  [SEG_CARGO + 2 * 5 + 2] = { 0, 224, 106, 69, 13, 14 }, /* cargo-2-2 */
  [SEG_CARGO + 2 * 5 + 3] = { 14, 224, 119, 100, 13, 14 }, /* cargo-2-3 */
  [SEG_CARGO + 2 * 5 + 4] = { 28, 224, 118, 130, 13, 14 }, /* cargo-2-4 */
  [SEG_CARGO + 3 * 5 + 0] = { 21, 239, 49, 73, 14, 11 }, /* cargo-3-0 */
  [SEG_CARGO + 3 * 5 + 1] = { 36, 239, 84, 49, 14, 11 }, /* cargo-3-1 */
  [SEG_CARGO + 3 * 5 + 2] = { 51, 239, 120, 66, 14, 11 }, /* cargo-3-2 */
  [SEG_CARGO + 3 * 5 + 3] = { 66, 239, 139, 99, 14, 11 }, /* cargo-3-3 */
  [SEG_CARGO + 3 * 5 + 4] = { 81, 239, 143, 133, 14, 11 }, /* cargo-3-4 */
  [SEG_COLON] = { 96, 239, 145, 13, 3, 10 }, /* colon */
  [SEG_DIGIT + 0 * 7 + 0] = { 12, 259, 110, 8, 11, 3 }, /* digit-0-a */
  [SEG_DIGIT + 0 * 7 + 1] = { 100, 239, 119, 9, 4, 9 }, /* digit-0-b */
  [SEG_DIGIT + 0 * 7 + 2] = { 105, 239, 119, 18, 4, 9 }, /* digit-0-c */
  [SEG_DIGIT + 0 * 7 + 3] = { 24, 259, 110, 25, 11, 3 }, /* digit-0-d */
  [SEG_DIGIT + 0 * 7 + 4] = { 110, 239, 108, 18, 4, 9 }, /* digit-0-e */
  [SEG_DIGIT + 0 * 7 + 5] = { 115, 239, 108, 9, 4, 9 }, /* digit-0-f */
  [SEG_DIGIT + 0 * 7 + 6] = { 154, 251, 110, 16, 11, 4 }, /* digit-0-g */
  [SEG_DIGIT + 1 * 7 + 0] = { 36, 259, 128, 8, 11, 3 }, /* digit-1-a */
  [SEG_DIGIT + 1 * 7 + 1] = { 120, 239, 137, 9, 4, 9 }, /* digit-1-b */
  [SEG_DIGIT + 1 * 7 + 2] = { 125, 239, 137, 18, 4, 9 }, /* digit-1-c */
  [SEG_DIGIT + 1 * 7 + 3] = { 48, 259, 128, 25, 11, 3 }, /* digit-1-d */
  [SEG_DIGIT + 1 * 7 + 4] = { 130, 239, 126, 18, 4, 9 }, /* digit-1-e */
  [SEG_DIGIT + 1 * 7 + 5] = { 135, 239, 126, 9, 4, 9 }, /* digit-1-f */
  [SEG_DIGIT + 1 * 7 + 6] = { 166, 251, 128, 16, 11, 4 }, /* digit-1-g */
  [SEG_DIGIT + 2 * 7 + 0] = { 60, 259, 152, 8, 11, 3 }, /* digit-2-a */
  [SEG_DIGIT + 2 * 7 + 1] = { 140, 239, 161, 9, 4, 9 }, /* digit-2-b */
  [SEG_DIGIT + 2 * 7 + 2] = { 145, 239, 161, 18, 4, 9 }, /* digit-2-c */
  [SEG_DIGIT + 2 * 7 + 3] = { 72, 259, 152, 25, 11, 3 }, /* digit-2-d */
  [SEG_DIGIT + 2 * 7 + 4] = { 150, 239, 150, 18, 4, 9 }, /* digit-2-e */
  [SEG_DIGIT + 2 * 7 + 5] = { 155, 239, 150, 9, 4, 9 }, /* digit-2-f */
  [SEG_DIGIT + 2 * 7 + 6] = { 178, 251, 152, 16, 11, 4 }, /* digit-2-g */
  [SEG_DIGIT + 3 * 7 + 0] = { 84, 259, 170, 8, 11, 3 }, /* digit-3-a */
  [SEG_DIGIT + 3 * 7 + 1] = { 160, 239, 179, 9, 4, 9 }, /* digit-3-b */
  [SEG_DIGIT + 3 * 7 + 2] = { 165, 239, 179, 18, 4, 9 }, /* digit-3-c */
  [SEG_DIGIT + 3 * 7 + 3] = { 96, 259, 170, 25, 11, 3 }, /* digit-3-d */
  [SEG_DIGIT + 3 * 7 + 4] = { 170, 239, 168, 18, 4, 9 }, /* digit-3-e */
  [SEG_DIGIT + 3 * 7 + 5] = { 175, 239, 168, 9, 4, 9 }, /* digit-3-f */
  [SEG_DIGIT + 3 * 7 + 6] = { 0, 259, 170, 16, 11, 4 }, /* digit-3-g */
  [SEG_GAME_A] = { 60, 251, 5, 4, 23, 5 }, /* game-a */
  [SEG_GAME_B] = { 84, 251, 5, 14, 23, 5 }, /* game-b */
  [SEG_HI] = { 146, 251, 80, 7, 7, 5 }, /* hi */
  [SEG_MISS + 0] = { 102, 224, 139, 30, 8, 12 }, /* miss-0 */
  [SEG_MISS + 1] = { 111, 224, 152, 30, 8, 12 }, /* miss-1 */
  [SEG_MISS + 2] = { 120, 224, 165, 30, 8, 12 }, /* miss-2 */
  [SEG_MISS_HALF] = { 129, 224, 178, 30, 5, 12 }, /* miss-half */
  [SEG_MISS_LABEL] = { 108, 251, 114, 35, 17, 5 }, /* miss-label */
  [SEG_OLIVE_BELL + 0] = { 129, 63, 26, 54, 26, 55 }, /* olive-bell-0 */
  [SEG_OLIVE_BELL + 1] = { 156, 63, 24, 55, 31, 54 }, /* olive-bell-1 */
  [SEG_OLIVE_READY] = { 37, 63, 24, 52, 29, 57 }, /* olive-ready */
  [SEG_OLIVE_THROW] = { 0, 122, 24, 56, 33, 53 }, /* olive-throw */
  [SEG_PM] = { 136, 251, 186, 20, 9, 5 }, /* pm */
  [SEG_POPEYE + 0] = { 80, 122, 43, 139, 45, 48 }, /* popeye-0 */
  [SEG_POPEYE + 1] = { 132, 0, 68, 129, 36, 58 }, /* popeye-1 */
  [SEG_POPEYE + 2] = { 0, 0, 79, 125, 41, 62 }, /* popeye-2 */
  [SEG_POPEYE + 3] = { 0, 63, 96, 129, 36, 58 }, /* popeye-3 */
  [SEG_POPEYE + 4] = { 126, 122, 112, 139, 45, 48 }, /* popeye-4 */
  [SEG_POPEYE_CATCH] = { 157, 176, 94, 120, 13, 16 }, /* popeye-catch */
  [SEG_POPEYE_DIZZY_LEFT] = { 67, 63, 35, 131, 30, 56 }, /* popeye-dizzy-left */
  [SEG_POPEYE_DIZZY_RIGHT] = { 98, 63, 135, 131, 30, 56 }, /* popeye-dizzy-right */
  [SEG_SPLASH + 0] = { 135, 224, 41, 200, 20, 11 }, /* splash-0 */
  [SEG_SPLASH + 1] = { 156, 224, 66, 200, 20, 11 }, /* splash-1 */
  [SEG_SPLASH + 2] = { 177, 224, 116, 200, 20, 11 }, /* splash-2 */
  [SEG_SPLASH + 3] = { 0, 239, 141, 200, 20, 11 }, /* splash-3 */
};

#endif
